<a href="https://colab.research.google.com/github/komazawa-deep-learning/komazawa-deep-learning.github.io/blob/master/notebooks/220komazawa_miniumXOR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<!-- # [駒澤大学心理学特講IIIAディープラーニングの心理学的解釈](https://www.komazawa-u.ac.jp/~kyoumu/syllabus_html/detail/074401.html) -->

# 最短ニューラルネットワークデモ

<div align='right'>
<a href='mailto:asakawa@ieee.org'>Shin Aasakawa</a>, all rights reserved.<br>
Date: 19/Apr/2019<br>
 MIT license
</div>

In [ ]:
import numpy as np                                 # numpy ライブラリの輸入
np.set_printoptions(precision=2)                   # 表示桁数の設定
np.random.seed(42)                                # 乱数系列の初期化
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
w0 = 2 * np.random.random((3,4)) - 1
w1 = 2 * np.random.random((4,1)) - 1
for i in range(3000):
    l1 = np.tanh(np.dot(X,w0))                     # tanh
    #l1 = 1/(1+np.exp(-(np.dot(X,w0))))            # sigmoid
    l2 = 1/(1+np.exp(-(np.dot(l1,w1))))
    dl2 = (y - l2) * (l2 * (1 - l2))
    dl1 = dl2.dot(w1.T) * (1 - l1 ** 2)            # tanh
    #dl1 = dl2.dot(w1.T) * (11 * (1-l1))           # sigmoid
    w1 += np.dot(l1.T, dl2)
    w0 += np.dot(X.T, dl1)
    print(l2.T) if i % 100 == 0 else None

In [ ]:
# 上の例は中間層から出力層へ行くバイアス項が無いので修正
import numpy as np
np.set_printoptions(precision=2)
np.random.seed(42)
n_hid = 10
X = np.array([ [0,0],[0,1],[1,0],[1,1]])
y = np.array([[0,1,1,0]]).T
b = np.ones((X.shape[0],1))
w1 = 2 * np.random.random((X.shape[1]+1, n_hid)) - 1
w2 = 2 * np.random.random((n_hid+1,y.shape[1])) - 1
iter_max = 3000
for i in range(iter_max):
    l1 = 1/(1+np.exp(-(np.dot(np.concatenate((X,b),axis=1),w1))))  # sigmoid
    #l1 = np.tanh(np.dot(np.concatenate((X,b),axis=1),w1))           # tanh
    l2 = 1/(1+np.exp(-(np.dot(np.concatenate((l1,b),axis=1),w2))))
    #dl2 = (y - l2) * (l2 * (1 - l2))                               # sigmoid
    dl2 = (y - l2) * (l2 - l2 **2)                                  # tanh
    dl1 = np.dot(dl2, w2.T) * (np.concatenate((l1,b),axis=1) * (1-np.concatenate((l1,b),axis=1)))
    w2 += np.dot(np.concatenate((l1,b),axis=1).T, dl2)
    w1 += np.dot(np.concatenate((X,b),axis=1).T, dl1[:,:-1])
    print(l2.T) if i % 100 == 0 else None
#print(l2.T)

----

他の手法を使うとどうなるか？

## ロジスティック回帰の場合

In [8]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X,y)
#print(model.score(X,y))
print(X, model.predict(X))

[[0 0]
 [0 1]
 [1 0]
 [1 1]] [0 0 0 0]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


---

## ランダムフォレストの場合


In [10]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X,y)

#model.score(X,y)
print(model.predict(X))

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


[0 1 1 0]


---

## SVM の場合


In [11]:
from sklearn.svm import SVC
model = SVC(kernel='rbf')
model.fit(X,y)

#model.score(X,y)
print(model.predict(X))

[0 1 1 0]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


---

### SVM の場合(2)

In [12]:
model = SVC(kernel='sigmoid')
model.fit(X,y)
#model.score(X,y)
model.predict(X)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 1, 1, 1])