# PCA

<center>
<img src="https://komazawa-deep-learning.github.io/assets/2021_1215olivetti_face_pca.svg" width="33%">
</center>    

最適化すべき目的関数 (損失関数)を以下のとおりとする。さらに，目的関数をパラメータ $\mathbf{w}$ で微分した場合を示した:
$$
\begin{aligned}
\ell &=\mathbf{w}^{\top}\mathbf{X}^{\top}\mathbf{Xw} -\lambda\left(\mathbf{w}^{\top}\mathbf{w}-1\right)\\
\frac{\partial\ell}{\partial\mathbf{w}} &= 2\mathbf{Xw}-2\lambda\mathbf{w}
\end{aligned}
$$

上式を 0 とおけば，固有値の定義と同一視することができる。$\mathbf{Xw}=\lambda\mathbf{w}$

## 一方，特異値分解 (SVD: singular values decompostion) を以下に示す

<center>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Singular-Value-Decomposition.svg/2560px-Singular-Value-Decomposition.svg.png" width="33%"><br/>
From wikipedia    
</center>

実在する $2\times2$ 行列 $\mathbf{M}$ の特異値分解 $\mathbf{U\Sigma V^{⁎ }}$ の説明図。<br/>

* 上: $\mathbf{M}$ の作用，すなわち単位円盤 D と 2 つの正規単位ベクトル $\mathbf{e}_ {1}$, $\mathbf{e}_ {2}$ 
への影響によって示される。<br/>
* 左: $\mathbf{D}, \mathbf{e}_{1}, \mathbf{e}_{2}$ に対する $\mathbf{V^{ ⁎}}$ の作用(回転) <br/>
* 下: $\mathbf{\Sigma}$ の作用，つまり特異値 $\sigma_{1}$ による水平方向のスケーリングと $\sigma_{2}$ による垂
直方向のスケーリング<br/>
* 右: $\mathbf{U}$ の作用，すなわち回転である。<br/>

2次元実数せん断変換の特異値分解（SVD）を視覚的に表現したもの。

図左上は，単位円盤を青で示し，2 つの正準単位ベクトルを表わしている。
右上は，単位円盤に対する $\mathbf{M}$ の作用を表す。
$\mathbf{M}$ は円を楕円に変形する。
SVD は $\mathbf{M}$ を 3 つの単純な変換に分解する。
すなわち，回転 $\mathbf{V^{* }}$, 座標軸に沿ったスケーリング $\mathbf{\Sigma}$, 2 回目の回転 $\mathbf{U}$ である。
SVD は，楕円の半長軸と半短軸の長さ $\sigma_{1}$ と $\sigma_{2}$ を明らかにする。
これらはちょうどスケーリング $\mathbf{\Sigma}$ の対角要素として現れる特異値。
楕円の座標軸に対する回転は $\mathbf{U}$ で与えられる。
ここで $\phi\doteqdot1.618$ は黄金比を示す。
$\sigma_{1}=\phi,\sigma_{2}=1/\phi,\mathbf{V}^{* }=\tan(\alpha)=\phi$ による $\alpha$ の時計回りの回転，すなわち，$\mathbf{V}$ は $-\alpha$ による回転。
$\mathbf{V}$ は $-\alpha\doteqdot58.28$° による回転。
$\mathbf{U}=\beta$ による反時計回りの回転，$\beta$ は $\tan(\beta)=\phi-1$, すなわち $\beta\approx31.72$° をたす。
$\mathbf{\Sigma}$ は一意だが，$\mathbf{V}$ と $\mathbf{U}$ は一意ではないことに注意。
$\mathbf{V}$ と $\mathbf{U}$ の両方に 180° の回転を加えたり，反射を加えたりすることができる。

* 線形代数学において，特異値分解 (SVD) は実数または複素数の行列の因数分解である。
正方正則行列の固有値分解を一般化したもので，任意の $m\times n$ 行列に適用される。極座標分解と関連する。

* 具体的には $m\times n$ 複素行列 $\mathbf{M}$ の特異値分解は $\times m$ 複素ユニタリー行列を $\mathbf{U}$，$n\times n$ 対角線上に非負の実数を持つ直交対角行列を $\mathbf{V}$，$n\times n$ 複素ユニタリー行列を $\mathbf{V}$ とすると，$\mathbf{U\Sigma V^{* }}$ の形で因数分解される。
$\mathbf{M}$ が実数の場合，$\mathbf{U}$ と $\mathbf{V}$ も実数の直交行列であることが保証される。
このような文脈では，SVD はしばしば $\mathbf{U\Sigma V^{\top}}$ と表記される。
* 対角線上の要素 $\sigma_{i}=\Sigma_{ii}$ を $\mathbf{M}$ の特異値と呼ぶ。
非ゼロの特異値の数は，$\mathbf{M}$ のランクと等しい。
$\mathbf{U}$ の列と $\mathbf{V}$ の列とは，それぞれ $\mathbf{M}$ の左特異ベクトルと右特異ベクトルと呼ばれる。
* SVD は一意ではない。
特異値 $\Sigma_{ii}$ が降順になるように分解を選択することは常に可能である。
この場合 $\mathbf{\Sigma}$ (ただし $\mathbf{U}$ と $\mathbf{V}$ は必ずではない) は $\mathbf{M}$ で一意に決まる。
* ここで $\mathbf{\Sigma}$ は $r\times r$ の正方対角線であり，$r\times r$ は $\mathbf{M}$ のランクであり，0 でない特異値のみを持つ。 
この変形では，$\mathbf{U}$ は $m\times r$ の半単射行列，$n\times r$ の半単射行列で，$\mathbf{U^{* }U}=\mathbf{V^{* }V} =\mathbf{I}_ {r}$ となる。
* SVD の数学的な応用としては，擬似逆行列の計算，行列の近似，行列のランク，範囲，ヌル空間の決定などがある。また，SVD は，信号処理，データの最小二乗法によるフィッティング，プロセス制御など，科学，工学，統計学のあらゆる分野で非常に有用である。



In [3]:
# X を n 行 m 列の行列として，列方向 m x m の相関係数行列を求める
import numpy as np
from sklearn.datasets import fetch_olivetti_faces
data = fetch_olivetti_faces()
X, y = data.data, data.target

x_bar = np.mean(X, axis=0)         # 各列の平均値を計算
X_bar = X - x_bar                  # 各列の平均値を減じて平均偏差ベクトルとする
Cov = X_bar.T @ X_bar / X.shape[0] # 共分散行列
x_std = np.std(X, axis=0)          # 各列の標準偏差
R = Cov / np.outer(x_std.T, x_std) # 共分散行列の各列を対応する標準偏差の積で除して相関係数行列にする
print(f'R.shape:{R.shape}')        # 確認用 相関係数行列のサイズ
print(f'R\n:{R[:3,:3]}')           # 確認用 相関係数行列の最初の 3 行 3 列を表示する

R2 = np.corrcoef(X.T)              # 上記を一行で行う numpy コマンド
print(f'R2\n:{R2[:3,:3]}')         # 結果の表示


def pca(X, n_dim = 5):
    """N 行 x D 列 の行列の PCA を実施"""
    (n, m) = X.shape  # 行列のサイズを取得
    #X = X - np.tile(np.mean(X, 0), (n, 1))  # X から
    X = X - np.mean(X, axis=0)
    (l, M) = np.linalg.eig(np.dot(X.T, X))
    Y = np.dot(X, M[:,0:n_dim])
    return Y

print(pca(X.T)[:3])

u, s, vh = np.linalg.svd(X_bar) # , full_matrices=True) # hermitian=True)
print(u.shape, s.shape, vh.shape)

R.shape:(4096, 4096)
R
:[[1.        0.9432168 0.8148691]
 [0.9432168 1.        0.9244308]
 [0.8148691 0.9244308 1.       ]]
R2
:[[1.         0.9432174  0.81486848]
 [0.9432174  1.         0.92443031]
 [0.81486848 0.92443031 1.        ]]
[[-2.7122395   2.1089823   0.77511555 -0.65840954 -0.15321285]
 [-1.9998537   2.291157    0.46459827 -0.59731185 -0.16248778]
 [-1.096947    2.4451728   0.09920792 -0.7813157  -0.07815762]]
(400, 400) (400,) (4096, 4096)
